### NumPy 学习笔记

In [4]:
import numpy as np

### numpy数组切片不复制内容,任何修改都是在原有数据上的修改

In [5]:


test = np.array([1,2,3,4,56,7])
t = test[0:3]
t[:] = 99
print(test)
print(t)


[99 99 99  4 56  7]
[99 99 99]


### 多维数组引用,testq\[0\]\[1\] 和testq\[0,1\]是等价的

In [10]:
testq = np.array([[1,2],[3,4]])
print(testq[0][1])
print(testq[0,1])

2
2


### 数组切片

In [20]:
test3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
print(test3d[:2])
print('-----------')
print(test3d[:2,2:])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
-----------
[[[ 7  8  9]]

 [[17 18 19]]]


### 布尔索引,使用布尔索引，获取的是取值为true的那一行数据组成的nparray

In [21]:
test3d<20

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [29]:
from numpy.random import randn

test2 = randn(7,4)
print(test2)

[[-1.71359176 -2.38007328 -1.38932841 -1.59874946]
 [ 1.60482981 -1.53558939 -1.43562036 -1.09358531]
 [ 0.25055636 -0.61045731  0.43439177 -1.05898241]
 [ 2.86797175 -0.51506691  0.34538302  0.29297211]
 [-0.66610671  0.35435272  0.7505264  -1.07247449]
 [-0.13557503  0.16357908  2.40410525 -0.68147658]
 [-1.46577127 -1.03759364  0.8511618  -0.1967525 ]]


In [30]:
b = np.array(['qq','sina','baidu','ali','sohu','bili','sd'])
b=='qq'

array([ True, False, False, False, False, False, False])

In [31]:
test2[b=='qq']

array([[-1.71359176, -2.38007328, -1.38932841, -1.59874946]])

In [35]:
test2[(b!='qq')]

array([[ 1.60482981, -1.53558939, -1.43562036, -1.09358531],
       [ 0.25055636, -0.61045731,  0.43439177, -1.05898241],
       [ 2.86797175, -0.51506691,  0.34538302,  0.29297211],
       [-0.66610671,  0.35435272,  0.7505264 , -1.07247449],
       [-0.13557503,  0.16357908,  2.40410525, -0.68147658],
       [-1.46577127, -1.03759364,  0.8511618 , -0.1967525 ]])

In [41]:
# 布尔数组可以进行与& 或| 运算
m = (b!='qq') & (b!='sina')

### 是用reshape构造数组

In [45]:
test = np.arange(10).reshape(2,5)

In [46]:
test

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数组转置运算

矩阵转置操作，返回的是矩阵的视图，不会进行数据复制

In [47]:
test.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [48]:
test.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [49]:
## 矩阵内积
np.dot(test.T,test)

array([[25, 30, 35, 40, 45],
       [30, 37, 44, 51, 58],
       [35, 44, 53, 62, 71],
       [40, 51, 62, 73, 84],
       [45, 58, 71, 84, 97]])

### 通用函数（ufunc）

通用函数是npdarray 执行元素及操作的函数。（可看做简单函数，参数接受ndarray的扩展），比如np.sqrt

np.where 是三元运算矢量版本

In [56]:
np.where(test<0,1,3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [54]:
test.shape

(2, 5)

In [57]:
test

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
np.where(test<1,1,2)

array([[1, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [59]:
np.where(test<1,1,test)

array([[1, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数学统计

In [60]:
## 求和
test.sum()

45

In [65]:
## 平均值
print(test.mean())
print(np.mean(test))

4.5
4.5


In [68]:
## 标准差
print(test.std())
print(np.std(test))
## 方差
print(test.var())
print(np.var(test))


2.8722813232690143
2.8722813232690143
8.25
8.25


mean,sum 可以接受axis参数，用于指定轴

### 布尔数组方法

In [69]:
## any,用于判断是否存在一个True
(test>5).any()

True

In [71]:
## all 用于判断是否所有未True
(test>=0).all()

True

### 数组排序

In [72]:
test.sort(axis=1)

In [73]:
test

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
test = np.array([[3,4,7],[6,2,3]])

In [89]:
test

array([[3, 4, 7],
       [6, 2, 3]])

In [90]:
test.sort(axis=1)

In [91]:
test

array([[3, 4, 7],
       [2, 3, 6]])

In [92]:
test.sort(axis=0)

In [93]:
test

array([[2, 3, 6],
       [3, 4, 7]])

### 读取文件

numpy 保存文件np.save("test.npy",arr)

保存压缩文件np.savez("test.npz",a=arr),必须制定名称，load的时候根据名称获取数据

读取文件np.load("test.npy")

读取压缩文件是延时加载,返回的是一个对象

In [94]:
arr = np.arange(10)
np.save("test.npy",arr)

In [95]:
np.load("test.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.savez("test.npz",a=arr)

In [103]:
np.load("test.npz")

In [104]:
t=np.load("test.npz")

In [105]:
t['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy可以从txt加载数组

np.loadtxt

np.genfromtxt
